### PR TITLE
✨Adding ctors to Motor_Group

### PR DESCRIPTION
**Pull request by aaryan-gautam**
#470

### CODE REVIEW

**Comment by djava** [comment]
How is this different from my pr?

**Comment by WillXuCodes** [comment]
Be sure to credit @djava as a co-author, I think he's just opening this on PROS 4 instead of PROS 3.

**Comment by WillXuCodes** [comment]
also... needs doxygen comments

**Comment by djava** [comment]
Pros 4 motor groups are totally different though, shouldn't that just go in #489?

**Comment by WillXuCodes** [comment]
> Pros 4 motor groups are totally different though, shouldn't that just go in #489?

yeah after #489 gets merged we'll actually take a look at this, ideally this work should've been done on that PR branch but this works too.

**Comment by noam987** [comment]
This is for PROS 3.8 This Is taking @djava's PR and ensuring it is fully backwards compatible with PROS 3.7. While we could have requested changes on your PR,  with the timeline of pros 3.8 I felt it was simpler to have one of our members to do it that way. There definitely should be credit given to @djava . (I haven't reviewed this yet, but that was the intention when assigning this task)

**Comment by WillXuCodes** [comment]
Closed as duplicate to #470

**Pull request closed without merging**
