### PR TITLE
:sparkles: Allow adding functions to be called during initialize

### PR DESCRIPTION
**Pull request by ion098**
#### Test Plan:

- [ ] test item

### CODE REVIEW

**Comment by liam-teale** [comment]
@Rocky14683 could you share the zip file so I can test

**Comment by Rocky14683** [comment]
[Download link](https://artprodcus3.artifacts.visualstudio.com/A268c8aad-3bb0-47d2-9a57-cf06a843d2e8/a421d041-2579-4bf8-a0aa-d7a0307dade3/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3B1cmR1ZS1hY20tc2lnYm90cy9wcm9qZWN0SWQvYTQyMWQwNDEtMjU3OS00YmY4LWEwYWEtZDdhMDMwN2RhZGUzL2J1aWxkSWQvNjU1OS9hcnRpZmFjdE5hbWUvdGVtcGxhdGU1/content?format=zip)

**Comment by ion098** [comment]
Turns out tasks can be safely started in global ctors, so this PR has no purpose lol.

**Pull request closed without merging**
