### PR TITLE
fix makefile override bug

### PR DESCRIPTION
**Pull request by Rocky14683**

### CODE REVIEW

**Comment by liam-teale** [comment]
What bug does this fix?

**Comment by Rocky14683** [comment]
Im just checking thats why this is a draft. Azure pipeline doesnt like your makefile override change

**Comment by Rocky14683** [comment]
yeh it works

**Comment by liam-teale** [comment]
Doesn't this indicate a problem with the pipeline, not the commit? Considering it builds fine on other platforms

**Comment by Rocky14683** [comment]
yeh im just trying to locate the problem

**Comment by liam-teale** [comment]
Gotta protect my code from rocky /j

**Comment by Rocky14683** [comment]
uh it end up also doesnt work on my computer, after i run make clean && make all

**Comment by AndrewLuGit** [comment]
Yeah, after changing the makefile rules it no longer runs patch_sdk_headers

**Review by AndrewLuGit — APPROVED** [review]
Works

**Pull request merged**
