### PR TITLE
Rebuild when dependent headers change

### PR DESCRIPTION
**Pull request by PixelToast**
Uses the gcc/g++ -M flag to generate header dependancies which get
thrown in deps/ and included next build

This is the most efficient solution where ONLY the source files that
depend on a header are recompiled versus doing a clean build on the
entire project

Should fix a LOT of random bugs people are getting when modifying
headers even including segfaults from discontinuity between function
signatures

Right now only tested on Linux with GCC 5.4.1
Both C and C++ tested
Subdirectories tested

<3

### CODE REVIEW

**Comment by HotelCalifornia** [comment]
You need to make sure that gnu++17 is specified for c++ standard and I'm not sure why `version` is part of the `all` rule

**Comment by HotelCalifornia** [comment]
And test with gcc 7.2.1 or higher

**Comment by PixelToast** [comment]
I'm a bit confused, I did not change any of the flags or the all rule
https://github.com/purduesigbots/pros/blob/master/Makefile#L51
https://github.com/purduesigbots/pros/blob/master/common.mk#L17

**Comment by PixelToast** [comment]
Tested on windows
GNU Make 4.2.1
GCC 7.2.1

**Comment by HotelCalifornia** [comment]
@PixelToast if you want to reopen this, you'll have to make a new PR and have it target the cortex-master branch

**Comment by HotelCalifornia** [comment]
JK, you can make the PR on purduesigbots/pros2

**Pull request closed without merging**
