### PR TITLE
Pros4/feature/converting constructor

### PR DESCRIPTION
**Pull request by ryan-doan**
#### Summary:

Add dynamic instantiation by a device constructor that takes another device object

##### References (optional):

 PROS 4.0.4: Add Converting Constructors for Each Device Class #569 

#### Test Plan:

- [x] Compile
- [x] Create a device object with a different subclass which is used to instantiate a device object of another subclass. Is_installed is then called to verify conversion is successful.

### CODE REVIEW

**Review by noam987 — CHANGES_REQUESTED** [review]
1. In my opinion these constructors should take in device references, not devices.
 2. This did not pass my simple hardware testing (make a motor, cast it to a device, recast it to a motor then try to spin it), as it did not create a motor object. this is an issue with all the devices

**Comment by aberiggs** [comment]
LGTM

**Review by aberiggs — APPROVED** [review]
LGTM

**Comment by noam987** [comment]
I'm going to wait with this until after initial open beta release. We need to think about whether or not some of the devices need to be be explicit constructors or not. This is not critical or a major bug for initial release, more of a QOL feature

**Comment by noam987** [comment]
Stale PR

**Pull request closed without merging**
